---

server:
  port: ${port:8082}

# Spring config
spring:
  gson:
    serialize-nulls: false
    exclude-fields-without-expose-annotation: true
  http:
    converters:
      preferred-json-mapper: gson

# Cloud Foundry
cloud-foundry:
  appName: ${vcap.application.application_name}
  appUri: ${vcap.application.application_uris[0]}
  api: ${vcap.application.cf_api}
  org: ${vcap.application.organization_name}
  space: ${vcap.application.space_name}
  user: ${cfUser}
  pass: ${cfPass}
  encKey: ${encKey}
  encVec: ${encVec}