---

server:
  port : 8081

# Spring config
spring:
  gson:
    serialize-nulls: false
    exclude-fields-without-expose-annotation: true
  http:
    converters:
      preferred-json-mapper: gson
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:javadevant

# Logging config
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO

service-props:
  encKey: ${encKey}
  encVec: ${encVec}